### PR TITLE
Add .NET Standard Support

### PR DESCRIPTION
**Pull request by Game4all**
This pull request makes the CSharpOsu project .NET Standard compliant , which means it can be used both from .NET Framework projects & .NET Core Projects. So there's no need for the  CSharpOsuCore project anymore.

### CODE REVIEW

**Comment by Game4all** [comment]
I also forgot to point that this PR also makes OsuClient instances reuse a same webclient instance between requests instead of creating a new one on each request

**Comment by Xferno2** [comment]
Hello, sorry for not answering I no longer check my project regularly. Every thing looks good but I'd rather declare the WebClient internally, inside the library than to supply my own WebClient when creating an instance. Just so I don't brick the code for everyone using the library. I will rewrite the code and submit to this pull soon.

**Comment by Game4all** [comment]
It's totally fine. It is not like I opened this PR ages ago and it doesn't matter as long as you reply :smiley:

**Comment by Xferno2** [comment]
For the past few days I started rewriting some of the code in the library. I wanted to ask if you would allow me to use some code from your circles.NET library, mostly CreateURL function and the mods converter? I will write credits in comments where I used your code.

Also once I finished and pushed the update, can you change the project from .NET core to a .NET standard because I have no clue how to do that?

**Comment by Game4all** [comment]
Sure , you can ! (It is open-source after all).
I will change the project type to standard once you pushed the changes

**Comment by Xferno2** [comment]
I finally finished, I will merge with master as soon as you change the .NET to standard.
EDIT: nvm I realized you cannot download pull request. I will create a new branch.

**Comment by Game4all** [comment]
Before merging are you sure you want the webclient in [`CSharpOsu.cs#L21`](https://github.com/Game4all/CSharpOsu/blob/net-standard/CSharpOsu/CSharpOsu.cs#L21) to be static ?

 That means the same webclient instance will be reused for every `CSharpOsu` instance created (imagine the case where the user creates a CSharpOsu instance per thread to querry API in parallel, it will reuse one same webclient instance accross all CSharpOsu instances)

I think every CSharpOsu instance should have its own WebClient instance (created in CSharpOsu constructor?)

I wait for your thoughts on this

**Comment by Game4all** [comment]
I added the Example project to main solution file & bumped the framework version to 4.6.1 because 4.5.2 doesn't support netstandard projects

**Comment by Xferno2** [comment]
> Before merging are you sure you want the webclient in [`CSharpOsu.cs#L21`](https://github.com/Game4all/CSharpOsu/blob/net-standard/CSharpOsu/CSharpOsu.cs#L21) to be static ?
> 
> That means the same webclient instance will be reused for every `CSharpOsu` instance created (imagine the case where the user creates a CSharpOsu instance per thread to querry API in parallel, it will reuse one same webclient instance accross all CSharpOsu instances)
> 
> I think every CSharpOsu instance should have its own WebClient instance (created in CSharpOsu constructor?)
> 
> I wait for your thoughts on this

Ah you're right, I'm pretty split on the decision to make it static or not. I wanted to make it easier for the user to code with it but your point is right, I will rewrite that.

**Comment by Xferno2** [comment]
Done, I found a way so both of us can be pleased. What's left is for you to do the magic thing to convert it to .NET standard.

I merged this pull with 4.9 branch, download it from there.

**Comment by Game4all** [comment]
It should be good now

**Comment by Xferno2** [comment]
> It should be good now

So everything is done and ready for the update?

**Comment by Game4all** [comment]
Yes 👍

**Comment by Xferno2** [comment]
Okay good, I will be working on documentation and nuget package and merge this pull with master asap.

**Comment by Xferno2** [comment]
All done, thanks a lot for the help.

**Comment by Game4all** [comment]
Thanks for merging !

**Comment by Xferno2** [comment]
:+1:

**Pull request merged**
